language: java
before_install:
- curl -L https://github.com/docker/compose/releases/download/3.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv ./docker-compose /usr/local/bin/docker-compose
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/project.jar -t coca1719/project234-backend  .
- docker push coca1719/project234-backend
- docker pull dto80/project234-frontend
script:
- docker-compose -H tcp://54.191.206.59:8025 up -d
cache:
 directories:
  - "$HOME/.m2"